create table public.bookmarks_news (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null default gen_random_uuid (),
  news_id uuid null default gen_random_uuid (),
  constraint bookmarks_news_pkey primary key (id)
) TABLESPACE pg_default;